version: "3.9"
services:
  arbitrage:
    image: arbitrage:v1.1.4
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: arbitrage
    hostname: arbitrage
    volumes:
      - ./.env:/arbitrage/.env
